workflows:
  flutter-android-workflow:
    name: Guardian SOS Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: flutter_project  # <--- THIS TELLS IT TO LOOK IN THE FOLDER
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-codesign
    artifacts:
      - flutter_project/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - omeratif06@gmail.com # Your email to receive the APK
